name: "Récupérer les photos"

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Créer le dossier public
        run: mkdir -p public
      - name: Récupérer les photos avec curl
        # highlight-next-line
        run: curl -o public/photos-data.json "https://api.slingacademy.com/v1/sample-data/photos?offset=10&limit=20"
      - name: Committer le fichier
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Mise à jour auto des photos"
          file_pattern: "public/photos-data.json"